### ISSUE TITLE
csv file does not give back network when requested 

### ISSUE THREAD

**Issue by xrise75** [EIDA/eida-statistics#21]
https://ws.resif.fr/eidaws/statistics/1//dataselect/query?start=2022-01&end=2022-12&datacenter=NOA&network=HP&aggregate_on=location,channel,month,datacenter,network,station,country&format=csv
[query.csv](https://github.com/EIDA/eida-statistics/files/10489889/query.csv)

Moreover format=text does not work. Only csv

**Comment by jschaeff** [comment]
If you aggregate on networks, you will have the result for all the networks.
If you want to see the statistics for each network, you need to remove the network from the "aggregate_on" parameter, which would give:

https://ws.resif.fr/eidaws/statistics/1//dataselect/query?start=2022-01&end=2022-12&datacenter=NOA&network=HP&aggregate_on=location,channel,month,datacenter,station,country&format=csv

What would you like a format text to look like ?

**Comment by xrise75** [comment]
Ok my fault about the network agregation

csv is fine for me as a simple choice BUT in the builder, when I choose format Text/csv then the url has ...&format-=text instead of csv and does not work

**Comment by jschaeff** [comment]
OK, nice catch, this is a bug. @vpet98 will fix it.

**Comment by vpet98** [comment]
Thank you for the note,

Bug is fixed on main branch. Needs to be deployed again I suppose.

**Comment by vpet98** [comment]
Yes, I can, but what we would like to reply in this case? Maybe print the wrong value as well?

**Comment by jschaeff** [comment]
something like "Unsupported value for parameter format." would do, I guess ?

**Comment by vpet98** [comment]
Done!

**Comment by xrise75** [comment]
Not fixed yet!
still when in query form I click format text/csv then the url given has "&format=text" instead of "&format=csv"

**Comment by vpet98** [comment]
The code is fixed. New version is not deployed yet. I suppose it will be deployed soon together with some other fixes which are in progress.

**Comment by jschaeff** [comment]
Fix deployed.
Thank you @vpet98
